name: Package And Release

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      description:
        description: 'description'
        required: true
        default: 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
         npm install
         npm run build
         zip -r linker_fe.zip dist/
      - uses: actions/upload-artifact@v3
        with:
          name: webpack artifacts
          path: dist/

